add result Routes
mindtastic/motivator-service pull request #10
Opened 2022-07-03 02:04 UTC by alexfritsch10

Fixes #7 

As @theEpsilon already worked on the middleware of this service, which can be seen in this PR #9, I didnt implement this again.

2022-07-03 08:15 UTC, jgraeger requested changes
- Please move you're code to a [seperate express router](https://expressjs.com/de/guide/routing.html#express-router), as it's done in #9. This keeps our `index.ts` file clean. Enough complex stuff will be going on there.
- Please add validation on the entity provided with the `POST` request, so according to the API spec.
- See further comments and suggestion.

If that helps, you can auto generate code from the API spec and use it as an inspiration using `openapi-generator` (Albatrouz is also using this tool). It's a java program and can be installed via homebrew, but there is also a npm package `@openapitools/openapi-generator-cli` available (Please don't add it to the package.json dependencies if going for the latter :D). It includes generators for javascript and typescript server code, that you can use to *get inspiration* for your implementation. I would suggest going for the [typescript generator](https://openapi-generator.tech/docs/generators/typescript/), as it's supported by the project, gives you a little bit more safety and e.g. better autocompletion in your editor (if typescript is supported, like it is natively in vscode).

2022-07-03 08:15 UTC, jgraeger commented on src/index.ts
> +import * as db from './db';
Is there a specific reason why you changed the import to this? Having to prepend `default` to each db member, makes the code significantly less expressive

2022-07-03 08:15 UTC, jgraeger commented on src/index.ts
> +app.post('/motivator/result/:motivatorId', (req, res) => {
```suggestion
app.post('/motivator/:motivatorId/result', (req, res) => {
```
In the spec it's the other way around.

2022-07-03 08:15 UTC, jgraeger commented on src/index.ts
> +  }
`timestamp` is stated as a required field in the the API spec, but I like using the current server time and will change the spec accordingly :)

2022-07-03 08:15 UTC, jgraeger commented on src/index.ts
> +  }).then(() => res.status(204).send()).catch((err) => res.status(404).send(err));
This deletes **all** results of a motivator, not only the ones of the user!

2022-07-03 08:15 UTC, jgraeger commented on src/index.ts
> +  }).then(() => res.status(204).send()).catch((err) => res.status(404).send(err));
```suggestion
    where: { motivator_id: req.params.motivatorId },
  }).then(() => res.status(204).end()).catch((err) => res.status(404).end());
```
No request body for `404`.

Using send() on a 204 error is actually [fine according to the way it gets handles by express](https://github.com/expressjs/express/blob/master/lib/response.js#L111),although is not compliant with the express API. Use `end()` to send an empty response.

2022-07-03 08:15 UTC, jgraeger commented on src/index.ts
> +  }).then((result) => res.status(201).send(result)).catch((err) => res.status(404).send(err));
```suggestion
  }).then((result) => res.status(201).send(result)).catch((err) => res.status(404).end());
```
`404 No content` errors should not contain any request body according to spec. As a general remark, please keep in mind, that just dumping the Database error to the user could disclose sensitive information. Carefully check the documentation of the [underlying APIs used](https://sequelize.org/api/v6/identifiers.html#errors), if that could be the case.

2022-07-03 08:15 UTC, jgraeger commented on src/index.ts
> +    user_id: req.get('X-User-ID'),
Remember to use the middleware later. You mentionend this in your PR opening message, so it's fine :)

2022-07-03 08:15 UTC, jgraeger commented on src/index.ts
> +    res.status(422).send('Request body undefined');
```suggestion
    res.status(422).send({ error: 'Request body undefined'});
```
API stick required `422 Unprocessable entity` errors to return an object with the string property `error` containing the message.

2022-07-03 08:15 UTC, jgraeger commented on src/index.ts
> +    motivator_id: req.params.motivatorId,
This is not storing any user input submitted.

2022-07-06 21:20 UTC, alexfritsch10 commented
I opened a new PR on the branch "feature/gloriousResultRoutes" more building on what was already provided by @theEpsilon.

2022-07-06 21:20 UTC, closed without merging