add result routes
mindtastic/motivator-service pull request #16
Opened 2022-07-06 21:05 UTC by alexfritsch10

Fixes #7

2022-07-07 09:05 UTC, jgraeger requested changes
Please see individual comments. General remarks:

- If the promise chain becomes to overwhelming, we could think of switching to the `async/await` pattern.
- We have lots of error `500` catch clauses here. Use an [express error handling middleware](http://expressjs.com/en/guide/error-handling.html) instead. A default is already in place from the framework, however it returns HTML instead of JSON. See mindtastic/mood-diary#22 and mindtastic/mood-diary#21 for more information and implementations.
- Please test your implementation before requesting review! At least manually with the example requests from the API spec.

2022-07-07 09:05 UTC, jgraeger commented on src/router.js
> +    },
Just a comment: We should add an abstraction function to that query, to prevent ourselves from *forgetting* to query for the user id.

2022-07-07 09:05 UTC, jgraeger commented on src/router.js
> +  }).then((foundResult) => {
The `findOne()` call is not in a `then()` handler. Hence, `count()` and `findOne()` are executed concurrently and both are initiating a database query at the same. Furthermore, both `then()` handlers could write response headers. Writing to response headers after they got sent to the client (either by calling `send()` or `end()`) is impossible in the HTTP protocol and therefore causes errors when trying to do so in express (and would so in any other HTTP framework).

Did you test this in some way? If i try to delete for a non existing motivator, I instantaneously run into a crash caused by the described behaviour, although the (first) response is correct. As the request is served, the crash cannot be caught by the express default error handler, so the error actually brings down the whole application and needs to be completly restarted. 

### HTTP log
```bash
curl -X DELETE -v http://localhost:4545/motivator/12/result \
       -H 'X-User-Id: 5c6d7d31-2449-41dc-9441-d58737748fc8'

*   Trying 127.0.0.1:4545...
* Connected to localhost (127.0.0.1) port 4545 (#0)
> DELETE /motivator/12/result HTTP/1.1
> Host: localhost:4545
> User-Agent: curl/7.79.1
> Accept: */*
> X-User-Id: 5c6d7d31-2449-41dc-9441-d58737748fc8
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Date: Thu, 07 Jul 2022 08:01:37 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Content-Length: 0
``` 

### App log
```bash
headcoach          | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
headcoach          |     at new NodeError (node:internal/errors:388:5)
headcoach          |     at ServerResponse.setHeader (node:_http_outgoing:603:11)
headcoach          |     at ServerResponse.header (/app/node_modules/express/lib/response.js:794:10)
headcoach          |     at ServerResponse.json (/app/node_modules/express/lib/response.js:275:10)
headcoach          |     at ServerResponse.send (/app/node_modules/express/lib/response.js:162:21)
headcoach          |     at file:///app/src/router.js:121:37
headcoach          |     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
headcoach          |   code: 'ERR_HTTP_HEADERS_SENT'
headcoach          | }
headcoach-pgsql    | 2022-07-07 08:01:37.427 UTC [38] LOG:  could not receive data from client: Connection reset by peer
headcoach          | [nodemon] app crashed - waiting for file changes before starting...
```

2022-07-07 09:05 UTC, jgraeger commented on src/router.js
> +  }).then((result) => res.status(200).send(result))
```suggestion
  }).then((result) => res.status(201).send({ resultId: result.id, status: 'success' }))
```

Please keep you're responses compliant to the API spec.

2022-07-07 09:05 UTC, jgraeger commented on src/router.js
> +import postSchemaResult from './validation/schema_postMotivatorResult';
Naming could be more expressive. Just from reading the names , I don't know what they are. Same goes for `postSchema` of course :D

2022-07-07 09:05 UTC, jgraeger commented on src/router.js
>  import { checkSchema } from 'express-validator';
```suggestion
import { checkSchema, validationResult } from 'express-validator';
```
Also for @theEpsilon

2022-07-07 09:05 UTC, jgraeger commented on src/router.js
> +router.post('/', checkSchema(postSchemaMotivator), ((req, res) => {
```suggestion
router.post('/', checkSchema(postSchemaMotivator), ((req, res) => {
  const validationErrors = validationResult(req);
  if (!validationErrors.isEmpty()) {
    return res.status(422).send({ errors: validationErrors.array() });
  }
```

Also for @theEpsilon:

Just validating a schema is not enough. You have to actually fetch the result in your handler and do something with it. The proposed change is okay for this post route, as there is no specified error format in the API docs.

2022-07-07 09:05 UTC, jgraeger commented on src/router.js
> +  const newResultInput = { value: req.body.value };
Validation Error needs to be handled. See comment above.

2022-07-07 09:05 UTC, jgraeger commented on src/router.js
> +    status: req.body.status,
```suggestion
    status: 'completed',
```
According to the status is not something the user provides to us, we have to set it. For now, always settings `completed` is fine

2022-07-07 09:05 UTC, jgraeger commented on src/router.js
> +    feedback: req.body.feedback,
```suggestion
    feedback: req.body.feedback.rating,
```
According to the API spec `feedback` is an JSON object, not a string!

2022-07-07 09:05 UTC, jgraeger commented on src/router.js
> +  const newResultInput = { value: req.body.value };
```suggestion
  const newResultInput = { value: req.body.values };
```

2022-07-07 09:05 UTC, jgraeger commented on src/validation/schema_postMotivatorResult.js
> +  },
```suggestion
  values: {
    exists: true,
  },
```

Could we validate `value` a little bit more? I know it's hard, as long as there is no mechanism for you to fetch the actual inputs of a motivator, but the structure?

Like `values` is required to be an existing `object` with `0..n` key, value pairs, where keys could be parsed to integer `number` and the value is again an `object` with on property `entries` and so on...

2022-07-07 09:05 UTC, jgraeger commented on src/validation/schema_postMotivatorResult.js
> +  },
```suggestion
```
Status is no part of the request body!

2022-07-07 09:05 UTC, jgraeger commented on src/validation/schema_postMotivatorResult.js
> +  },
Feedback is supposed to be an `object` with a property `rating`. Also the error message is misleading.
```suggestion
  'feedback.rating': {
    notEmpty: true,
    isIn: {
      options: ['positive', 'neutral', 'negative'],
      errorMessage: 'The status has to be either completed or running',
    },
    errorMessage: 'Expected property feedback with feedback.values: `postive`|`neutral`|`negative`',
  },
```

2022-07-07 09:05 UTC, jgraeger commented on src/router.js
> +          },
~~This deletes the motivator results for all users! Not only the currently logged in one!~~

Sorry, the earlier comment is totally wrong. What I meant is: Is there a specific reason for the `if (numberResultInput > 0)` here? There SHOULD never be a case, that there is not `motivatorResultInput` for a given `motivatorResult` of the user, but why shouldn't we delete the result if there are no inputs in db? We could catch the case to log the event, as it indicates that something is going wrong.

2022-07-07 23:06 UTC, jgraeger commented
As requested in a meeting, I've restored are working branch of the state. The reason why it not started we're simply LOTS of syntactical errors. Remaks on my changes:

- Please check the changes in the schema file. Using `_` multiple times as in (`options: (input, { _, _, path })`) is forbidden in method definitions and in object decomposition (like in that case) not needed. Also not that `typeof` always returns the name of a JS primitive, so it can never become `JSON`. 
- `await` keyword can only be used in `async` functions. The route handlers we're not marked as async, so using the keyword was illegal --> App is not starting.
- The file `defaultError.js` got created in the `middlewares` folder, however it not contained middleware, but factory functions. This is misleading, as it made me think we actually would have a json error handling middleware (which would mean that we could remove all .catch() block for `500 Internal Server Error`s. I rewrote them as actual middleware.
- Delete should delete ALL results for a user, not only the last one. I’ve changed that.
- As we are performing multiple related deletions, I wrapped the deletion in a transaction
- Maybe we can do the deletion with a cascade option

2022-07-07 23:41 UTC, theEpsilon requested changes
Just revert the 2 changes, rest looks good :)

2022-07-07 23:41 UTC, theEpsilon commented on src/router.js
> +    }],
```suggestion
    include: [{ model: db.models.motivatorContent }],
```

Returning any result data here is not desired. This endpoint is only intended for fetching a motivator's general definition.

2022-07-07 23:41 UTC, theEpsilon commented on src/router.js
> +    }));
```suggestion
    }))
    .map(({ MotivatorContents, ...itemWithoutContents }) => ({
      ...itemWithoutContents,
    }));
```

see above. returning result data here is not desired. there is a reason I commented it out :)

2022-07-08 21:04 UTC, theEpsilon approved these changes

2022-07-08 21:05 UTC, merged